version: '3'

vars:
  CILIUM_VERSION: 1.19.0

tasks:
  generate-cilium-manifest:
    cmds:
      - |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
        helm template \
        cilium \
        cilium/cilium \
        --version {{ .CILIUM_VERSION }} \
        --namespace kube-system \
        --set ipam.mode=kubernetes \
        --set kubeProxyReplacement=true \
        --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
        --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
        --set operator.replicas=1 \
        --set cgroup.autoMount.enabled=false \
        --set cgroup.hostRoot=/sys/fs/cgroup \
        --set l2announcements.enabled=true \
        --set k8sClientRateLimit.qps=50 \
        --set k8sClientRateLimit.burst=100 \
        --set k8sServiceHost=localhost \
        --set k8sServicePort=7445 > ./cilium.yaml
